[hetzner]
type = sftp
host = u377059.your-storagebox.de
user = u377059
port = 23
key_file = /home/rgr/.ssh/id_rsa
shell_type = unix
md5sum_command = md5 -r
sha1sum_command = sha1 -r

[gdrive]
type = drive
client_id = 1018582420826-a8ap7uf2itij9v06vj1f2d29i34oc45m.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AfB_byC1m8O-actOs2d0lz7NhGkZQmKDowTkWL-z0KiP2ANXuItSBIb7gECVEAjIlJULZ5P2uA4R901OTEcDY0XFH3EC_S56TFGIuBgl6OSrc39dso0uWVm3UXIbwj9LJCeGTWgSp87sZ5EVBdKVMVa-kEopZc2fwAlWMQaCgYKAagSARESFQHGX2MiUcUfCeA6_Beb-mx-8dcN-A0173","token_type":"Bearer","refresh_token":"1//09MWp4VhzlR-1CgYIARAAGAkSNwF-L9IrxqnnQxqnhIIYRK8P6iPIboSbcSOBW06fWoxGmomv9BFxqthr1KQ_hJQQlnvHY8cl8XE","expiry":"2023-11-19T10:05:16.483742178+01:00"}
team_drive =
