[hetzner]
type = sftp
host = u377059.your-storagebox.de
user = u377059
port = 23
key_file = /home/rgr/.ssh/id_rsa
shell_type = unix
md5sum_command = md5 -r
sha1sum_command = sha1 -r

[gdrive]
type = drive
client_id = 1018582420826-a8ap7uf2itij9v06vj1f2d29i34oc45m.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AfB_byCpmZf884LUZZQLujVYZ7GtTr2wDrRsgX2PNvLhJxTToQhXlugp6gzZvcAM6seWu_zUZL0ECCVQBihlwPcFMPlPFsnG-TdBF89jtJe7iR702tZ1-8hcovx9Lwl_OI_ZZTP5Ho2YltE2NlqRhM1mLLFLh4uE5ksCaCgYKAYoSARESFQHGX2MiOLhLEkRLqK3TpXrmR6OlxQ0171","token_type":"Bearer","refresh_token":"1//098tIIVz7gujHCgYIARAAGAkSNwF-L9IrrJHH-MXUVUOqXQNaM1c0hegcNEhj9OGWVzvzTRmdRER0hF6fTs05-kImKwjFjaCZ9F4","expiry":"2023-11-29T15:02:18.790160909+01:00"}